version: 2
jobs:
  install-dependencies:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Download dependencies
          command: npm install --quiet
      - save_cache:
          paths: [node_modules]
          key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ./
          paths: [node_modules]
  build:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: npm run ci tests
          command: npm run ci
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - add_ssh_keys:
          fingerprints:
            - 'e9:f2:ef:eb:84:32:e1:2c:db:01:51:47:10:bb:85:83' # TO CHANGE!
      - setup_remote_docker
      - run:
          name: chmod +x scripts
          command: chmod +x .circleci/scripts/*.sh
      - run:
          name: run all scripts
          command: .circleci/scripts/run_all.sh
workflows:
  version: 2
  dependencies-and-deploy:
    jobs:
      - install-dependencies
      - build:
          requires: [install-dependencies]
      #- deploy:
      #    requires: [build]
      #    filters:
      #      branches:
      #        only: master
