version: 2
jobs:
  install-dependencies:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
        keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run:
        name: Download dependencies
        command: npm install --quiet
      - save_cache:
        paths: [node_modules]
        key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
        root: ./
        paths: [node_modules]
  build:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
        at: ./
      #- run:
      #  name: Generate static site
      #  command: npm start sed clean:dist filerev-all
      # See https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
      - run:
        name: run ci tests
        command: npm run ci
      - persist_to_workspace:
        root: ./
        paths: [dist]
workflows:
  version: 2
  dependencies-and-build:
    jobs:
      - install-dependencies
      - build:
          requires: [install-dependencies]
